version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://app_cuisine:5432/app_cuisine
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  webapp:
    build:
      context: ../../AppCuisine-frontend/docker
      dockerfile: ../../AppCuisine-frontend/docker/Dockerfile
    container_name: webapp
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_cuisine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge