version: "1.0"

services:
  postgres:
    container_name: postgres
    image: "postgres:14.7"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    hostname: postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-data: